name: Fetcher

on:
  schedule:
    - cron: '45 23 * * *' 
    - cron: '50 23 * * *' 
    - cron: '55 23 * * *' 
    - cron: '00 0 * * *'  
    - cron: '05 0 * * *'  
    - cron: '10 0 * * *' 
    - cron: '15 0 * * *' 



# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

permissions:
  contents: write


jobs:
  Get_Daily_Problem:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
      
      - name: Fetch Daily Problem from LeetCode
        run: python .github/scripts/Fetch_Daily_Problem.py
          
      - id: commit_files
        name: Commit files  
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: python ./.github/workflows/todo_List.py
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -am "GH Action Files added $(date)"
      - name: fetch from main
        run: git fetch origin main
      - name: push code to main
        run: git push origin HEAD:main

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  

