name: Daily Problem

on:
  schedule:
    - cron: '*/5 23,00 * * *' 



# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

permissions:
  contents: write


jobs:
  Get_Daily_Problem:
    runs-on: ubuntu-latest
    steps:
         
    - name: Commit and Push
      uses: devops-infra/action-commit-push@master
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        add_timestamp: true
        commit_prefix: "[AUTO]"
        commit_message: "Automatic commit"
        force: false
        target_branch: update/version
