name: Fetcher

on:
  schedule:
    - cron: '45 23 * * *' 
    - cron: '50 23 * * *' 
    - cron: '55 23 * * *' 
    - cron: '00 0 * * *'  
    - cron: '05 0 * * *'  
    - cron: '10 0 * * *' 
    - cron: '15 0 * * *' 



# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

permissions:
  contents: write


jobs:
  Get_Daily_Problem:
    runs-on: ubuntu-latest
    steps:
         
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: Fetch Daily Problem from LeetCode
        run: sudo python .github/scripts/Fetch_Daily_Problem.py
      
      - name: Commit and Add Changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          
          git add .
          git commit --allow-empty -am 'Add new daily problem'
          
          git push -f

      - name: Delete the solution again
        run: |
          git commit --allow-empty -am 'Add new daily problem'

          git push -f

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
