name: Daily Problem

on:
  schedule:
    - cron: '*/5 23,00 * * *' 



# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

permissions:
  contents: write


jobs:
  Get_Daily_Problem:
    runs-on: ubuntu-latest
    steps:
         
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add New Daily Challenge
          commit_user_name: 7oSkaaa # defaults to "github-actions[bot]"
          commit_user_email: ahmed.7oskaa@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
          add_options: '.'
          push_options: '--force-with-lease'
          skip_dirty_check: true    
          skip_fetch: false    
          skip_checkout: false
