name: Checkers

on:
  push:
  pull_request:
    
jobs:
  Checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Naming of files
        run: python .github/scripts/Naming_Checker.py
      - name: Check Author line of files
        run: python .github/scripts/Author_Checker.py
