name: README

on: workflow_dispatch

permissions:
  contents: write

jobs:
  README:
    environment: REAME_Update
    env:
      LINK: ${{secret.LINK}}
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: Update README with new Problem
        run: |
          echo "Store: ${{ env.LINK }}"
          LINK=${{ env.LINK }} python .github/scripts/README_Editor.py

      - name: Check if there are any changes
        id: verify_diff
        run: |
          if [ -n "$(git status --porcelain)" ]; 
          then echo "IS_VALID=true" >> $GITHUB_ENV;
          else echo "IS_VALID=false" >> $GITHUB_ENV;
          fi

      
      - name: Commit and Add Changes
        if: ${{ env.IS_VALID == 'true' }}
        run: |
          git config --global user.email "ahmed.7oSkaa@gmail.com"
          git config --global user.name "7oSkaaa"
          
          git add .
          git commit -am 'Add new daily problem'
          
      - name: Push
        if: ${{ env.IS_VALID == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force_with_lease: true
  